"""
Tekvwa Pro Audit - Support Ticket Model

Support ticket system for platform customer service.
Tracks inquiries, issues, and requests from tenant users.

Support Categories:
- Technical Issues (bugs, errors, integrations)
- Billing (payments, subscriptions, invoices)
- Compliance (NRS, VAT, PAYE questions)
- Feature Requests
- Account Management
"""

import uuid
from datetime import datetime, timedelta
from enum import Enum
from typing import TYPE_CHECKING, Optional, List

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, Integer, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.organization import Organization
    from app.models.user import User


class TicketCategory(str, Enum):
    """Category of support ticket."""
    TECHNICAL = "technical"           # Bugs, errors, system issues
    BILLING = "billing"               # Payments, subscriptions
    COMPLIANCE = "compliance"         # NRS, VAT, PAYE, tax questions
    FEATURE_REQUEST = "feature_request"  # New feature requests
    ACCOUNT = "account"               # Account management
    ONBOARDING = "onboarding"         # Setup and onboarding help
    TRAINING = "training"             # How-to questions
    INTEGRATION = "integration"       # API, webhooks, third-party
    SECURITY = "security"             # Security concerns
    OTHER = "other"


class TicketPriority(str, Enum):
    """Priority level of the ticket."""
    CRITICAL = "critical"    # System down, data loss risk
    HIGH = "high"            # Major functionality impacted
    MEDIUM = "medium"        # Normal priority
    LOW = "low"              # Minor issues, questions


class TicketStatus(str, Enum):
    """Status of the support ticket."""
    NEW = "new"                       # Just created
    OPEN = "open"                     # Assigned and being worked
    PENDING_CUSTOMER = "pending_customer"  # Waiting for customer response
    PENDING_INTERNAL = "pending_internal"  # Waiting for internal team
    IN_PROGRESS = "in_progress"       # Actively being resolved
    ON_HOLD = "on_hold"               # Temporarily paused
    RESOLVED = "resolved"             # Issue resolved
    CLOSED = "closed"                 # Ticket closed
    REOPENED = "reopened"             # Reopened after resolution


class TicketSource(str, Enum):
    """How the ticket was created."""
    WEB_PORTAL = "web_portal"         # Customer portal
    EMAIL = "email"                   # Email to support
    CHAT = "chat"                     # Live chat
    PHONE = "phone"                   # Phone call
    API = "api"                       # API integration
    SYSTEM = "system"                 # Auto-generated by system
    INTERNAL = "internal"             # Created by staff


class SupportTicket(BaseModel):
    """
    Support ticket for customer service.
    """
    __tablename__ = "support_tickets"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    
    # Ticket identification
    ticket_number: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique ticket number (e.g., TKT-2026-00001)"
    )
    
    # Organization and user
    organization_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    
    requester_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=False,
        index=True,
    )
    
    # Ticket details
    subject: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    
    category: Mapped[TicketCategory] = mapped_column(
        SQLEnum(TicketCategory),
        nullable=False,
        index=True,
    )
    
    priority: Mapped[TicketPriority] = mapped_column(
        SQLEnum(TicketPriority),
        nullable=False,
        default=TicketPriority.MEDIUM,
        index=True,
    )
    
    status: Mapped[TicketStatus] = mapped_column(
        SQLEnum(TicketStatus),
        nullable=False,
        default=TicketStatus.NEW,
        index=True,
    )
    
    source: Mapped[TicketSource] = mapped_column(
        SQLEnum(TicketSource),
        nullable=False,
        default=TicketSource.WEB_PORTAL,
    )
    
    # Tags for filtering
    tags: Mapped[Optional[List[str]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    
    # Assignment
    assigned_to_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    assigned_team: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="support, billing, technical, compliance"
    )
    
    assigned_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    # SLA tracking
    sla_due_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="SLA deadline"
    )
    
    sla_breached: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
    )
    
    first_response_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    first_response_sla_met: Mapped[Optional[bool]] = mapped_column(
        Boolean,
        nullable=True,
    )
    
    # Resolution
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    resolved_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    resolution_summary: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    
    resolution_code: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        comment="fixed, duplicate, wont_fix, not_reproducible, etc."
    )
    
    # Closure
    closed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    closed_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    # Customer satisfaction
    csat_rating: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="1-5 satisfaction rating"
    )
    
    csat_feedback: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    
    # Escalation
    escalated: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
    )
    
    escalated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    escalated_to_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    escalation_reason: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    
    # Related ticket (for duplicates/follow-ups)
    parent_ticket_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("support_tickets.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    # Attachments info
    has_attachments: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
    )
    
    # Internal notes (not visible to customer)
    internal_notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    
    # Context data
    context_data: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Browser info, page URL, error details, etc."
    )
    
    # Relationships
    organization: Mapped[Optional["Organization"]] = relationship(
        back_populates="support_tickets",
        lazy="selectin"
    )
    
    requester: Mapped["User"] = relationship(
        foreign_keys=[requester_id],
        lazy="selectin"
    )
    
    assigned_to: Mapped[Optional["User"]] = relationship(
        foreign_keys=[assigned_to_id],
        lazy="selectin"
    )
    
    resolved_by: Mapped[Optional["User"]] = relationship(
        foreign_keys=[resolved_by_id],
        lazy="selectin"
    )
    
    def __repr__(self) -> str:
        return f"<SupportTicket {self.ticket_number}: {self.subject[:30]}... ({self.status.value})>"
    
    @property
    def is_open(self) -> bool:
        """Check if ticket is still open."""
        return self.status not in [TicketStatus.RESOLVED, TicketStatus.CLOSED]
    
    @property
    def response_time(self) -> Optional[timedelta]:
        """Time to first response."""
        if self.first_response_at and self.created_at:
            return self.first_response_at - self.created_at
        return None
    
    @property
    def resolution_time(self) -> Optional[timedelta]:
        """Time to resolution."""
        if self.resolved_at and self.created_at:
            return self.resolved_at - self.created_at
        return None


class TicketComment(BaseModel):
    """Comments/replies on support tickets."""
    __tablename__ = "ticket_comments"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("support_tickets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    author_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
    )
    
    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    
    is_internal: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        comment="Internal notes not visible to customer"
    )
    
    is_from_customer: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
    )
    
    # Attachments
    attachments: Mapped[Optional[List[dict]]] = mapped_column(
        JSONB,
        nullable=True,
        comment="List of attachment metadata"
    )
    
    # Relationships
    ticket: Mapped["SupportTicket"] = relationship(lazy="selectin")
    author: Mapped["User"] = relationship(lazy="selectin")


class TicketAttachment(BaseModel):
    """Attachments for support tickets."""
    __tablename__ = "ticket_attachments"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("support_tickets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    comment_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("ticket_comments.id", ondelete="CASCADE"),
        nullable=True,
    )
    
    filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    
    file_path: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
    )
    
    file_size_bytes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )
    
    mime_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    
    uploaded_by_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
    )
    
    # Relationships
    ticket: Mapped["SupportTicket"] = relationship(lazy="selectin")
    uploaded_by: Mapped["User"] = relationship(lazy="selectin")
