"""
Tekvwa Pro Audit - Support Ticket Model

Support ticket system for platform customer service.
Tracks inquiries, issues, and requests from tenant users.

Support Categories:
- Technical Issues (bugs, errors, integrations)
- Billing (payments, subscriptions, invoices)
- Compliance (NRS, VAT, PAYE questions)
- Feature Requests
- Account Management
"""

import uuid
from datetime import datetime, timedelta
from enum import Enum
from typing import TYPE_CHECKING, Optional, List

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, Integer, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.organization import Organization
    from app.models.user import User


class TicketCategory(str, Enum):
    """Category of support ticket."""
    TECHNICAL = "technical"           # Bugs, errors, system issues
    BILLING = "billing"               # Payments, subscriptions
    COMPLIANCE = "compliance"         # NRS, VAT, PAYE, tax questions
    FEATURE_REQUEST = "feature_request"  # New feature requests
    ACCOUNT = "account"               # Account management
    ONBOARDING = "onboarding"         # Setup and onboarding help
    TRAINING = "training"             # How-to questions
    INTEGRATION = "integration"       # API, webhooks, third-party
    SECURITY = "security"             # Security concerns
    OTHER = "other"


class TicketPriority(str, Enum):
    """Priority level of the ticket."""
    CRITICAL = "critical"    # System down, data loss risk
    HIGH = "high"            # Major functionality impacted
    MEDIUM = "medium"        # Normal priority
    LOW = "low"              # Minor issues, questions


class TicketStatus(str, Enum):
    """Status of the support ticket."""
    NEW = "new"                       # Just created
    OPEN = "open"                     # Assigned and being worked
    PENDING_CUSTOMER = "pending_customer"  # Waiting for customer response
    PENDING_INTERNAL = "pending_internal"  # Waiting for internal team
    IN_PROGRESS = "in_progress"       # Actively being resolved
    ON_HOLD = "on_hold"               # Temporarily paused
    RESOLVED = "resolved"             # Issue resolved
    CLOSED = "closed"                 # Ticket closed
    REOPENED = "reopened"             # Reopened after resolution


class TicketSource(str, Enum):
    """How the ticket was created."""
    WEB_PORTAL = "web_portal"         # Customer portal
    EMAIL = "email"                   # Email to support
    CHAT = "chat"                     # Live chat
    PHONE = "phone"                   # Phone call
    API = "api"                       # API integration
    SYSTEM = "system"                 # Auto-generated by system
    INTERNAL = "internal"             # Created by staff


class SupportTicket(BaseModel):
    """
    Support ticket for customer service.

    Finding 50 (docs/FINDING_50_SCOPE.md): this model previously declared a large set of fields
    with zero real usage anywhere in the codebase (requester_id -- NOT NULL, with no matching DB
    column at all -- assigned_team/assigned_at/first_response_sla_met/resolution_summary/
    resolution_code/closed_at/closed_by_id/csat_rating/csat_feedback/escalated/escalated_to_id/
    parent_ticket_id/has_attachments/internal_notes/context_data), while
    app/services/support_ticket_service.py's create_ticket() (the only real construction site)
    and app/routers/support_tickets.py's own TicketResponse schema both already used the live
    table's real column names directly (reporter_user_id/reporter_email/reporter_name/
    is_escalated/escalation_level/resolution_notes/response_time_minutes/
    resolution_time_minutes/satisfaction_rating/satisfaction_feedback) -- confirmed crashing with
    UndefinedColumnError on every create, and would have failed Pydantic response validation on
    every read even if a row existed. Rewritten to match the live table and real usage exactly
    (option (B)). Needed zero migration.
    """
    __tablename__ = "support_tickets"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # Ticket identification
    ticket_number: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique ticket number (e.g., TKT-2026-00001)"
    )

    # Organization and reporter
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    reporter_user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    reporter_email: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    reporter_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Ticket details
    subject: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    category: Mapped[TicketCategory] = mapped_column(
        SQLEnum(TicketCategory),
        nullable=False,
        index=True,
    )

    priority: Mapped[TicketPriority] = mapped_column(
        SQLEnum(TicketPriority),
        nullable=False,
        default=TicketPriority.MEDIUM,
        index=True,
    )

    status: Mapped[TicketStatus] = mapped_column(
        SQLEnum(TicketStatus),
        nullable=False,
        default=TicketStatus.NEW,
        index=True,
    )

    source: Mapped[Optional[TicketSource]] = mapped_column(
        SQLEnum(TicketSource),
        nullable=True,
        default=TicketSource.WEB_PORTAL,
    )

    # Tags for filtering
    tags: Mapped[Optional[List[str]]] = mapped_column(
        JSONB,
        nullable=True,
    )

    # Assignment
    assigned_to_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    # SLA tracking
    sla_due_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="SLA deadline"
    )

    sla_breached: Mapped[Optional[bool]] = mapped_column(
        Boolean,
        default=False,
    )

    first_response_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    response_time_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Resolution
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    resolved_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    resolution_notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )

    resolution_time_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Customer satisfaction
    satisfaction_rating: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="1-5 satisfaction rating"
    )

    satisfaction_feedback: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )

    # Escalation
    is_escalated: Mapped[Optional[bool]] = mapped_column(
        Boolean,
        default=False,
    )

    escalated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    escalation_level: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    escalation_reason: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )

    # Relationships
    organization: Mapped[Optional["Organization"]] = relationship(
        back_populates="support_tickets",
        lazy="selectin"
    )

    reporter: Mapped[Optional["User"]] = relationship(
        foreign_keys=[reporter_user_id],
        lazy="selectin"
    )

    assigned_to: Mapped[Optional["User"]] = relationship(
        foreign_keys=[assigned_to_id],
        lazy="selectin"
    )

    resolved_by: Mapped[Optional["User"]] = relationship(
        foreign_keys=[resolved_by_id],
        lazy="selectin"
    )
    
    def __repr__(self) -> str:
        return f"<SupportTicket {self.ticket_number}: {self.subject[:30]}... ({self.status.value})>"
    
    @property
    def is_open(self) -> bool:
        """Check if ticket is still open."""
        return self.status not in [TicketStatus.RESOLVED, TicketStatus.CLOSED]
    
    @property
    def response_time(self) -> Optional[timedelta]:
        """Time to first response."""
        if self.first_response_at and self.created_at:
            return self.first_response_at - self.created_at
        return None
    
    @property
    def resolution_time(self) -> Optional[timedelta]:
        """Time to resolution."""
        if self.resolved_at and self.created_at:
            return self.resolved_at - self.created_at
        return None


class TicketComment(BaseModel):
    """
    Comments/replies on support tickets.

    Finding 50 (docs/FINDING_50_SCOPE.md): this model previously declared ticket_id/author_id
    (NOT NULL)/content/is_from_customer/attachments, none of which existed on the live table
    (which instead has support_ticket_id and two separate nullable author FKs, staff_id/user_id,
    plus comment). app/services/support_ticket_service.py's add_comment() (the only real
    construction site) already used the live table's real names directly -- confirmed crashing
    with UndefinedColumnError on every call. Rewritten to match (option (B)). Needed zero
    migration.
    """
    __tablename__ = "ticket_comments"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    support_ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("support_tickets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    staff_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    comment: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    is_internal: Mapped[Optional[bool]] = mapped_column(
        Boolean,
        default=False,
        comment="Internal notes not visible to customer"
    )

    # Relationships
    ticket: Mapped["SupportTicket"] = relationship(
        foreign_keys=[support_ticket_id], lazy="selectin",
    )
    staff: Mapped[Optional["User"]] = relationship(foreign_keys=[staff_id], lazy="selectin")
    user: Mapped[Optional["User"]] = relationship(foreign_keys=[user_id], lazy="selectin")


class TicketAttachment(BaseModel):
    """
    Attachments for support tickets.

    Finding 50 (docs/FINDING_50_SCOPE.md): this model previously declared ticket_id/comment_id
    (fictional, no DB equivalent)/file_size_bytes/mime_type/uploaded_by_id (NOT NULL), none of
    which existed on the live table (which instead has support_ticket_id/file_size/content_type
    and two separate nullable uploader FKs, uploaded_by_staff_id/uploaded_by_user_id).
    app/services/support_ticket_service.py's add_attachment() (the only real construction site)
    already used the live table's real names directly -- confirmed crashing with
    UndefinedColumnError on every call. Rewritten to match (option (B)). Needed zero migration.
    """
    __tablename__ = "ticket_attachments"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    support_ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("support_tickets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    file_path: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
    )

    file_size: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
    )

    content_type: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )

    uploaded_by_staff_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    uploaded_by_user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Relationships
    ticket: Mapped["SupportTicket"] = relationship(
        foreign_keys=[support_ticket_id], lazy="selectin",
    )
    uploaded_by_staff: Mapped[Optional["User"]] = relationship(
        foreign_keys=[uploaded_by_staff_id], lazy="selectin",
    )
    uploaded_by_user: Mapped[Optional["User"]] = relationship(
        foreign_keys=[uploaded_by_user_id], lazy="selectin",
    )
